### ISSUE TITLE
Release 0.10 checklist

### ISSUE THREAD

**Issue by jsamr** [typeskill/typer#1]
- [x]  setup expo snap
- [x] update line selected line attribute on some text operations #6
- [x] fix ineffective text attribute disabling #7
- [x] fix selection discrepancy after applying line type prefix modifier #8
- [x] fix keyboard suggested text gets overridden #5
- [x] fix Inserting a newline character in the middle of a line breaks one char off #11
- [x] fix deleting a list prefix character is poorly handled #12
- [x] expose methods to initialize and listen to delta changes
- [x] expose `extractTextFromDelta` method
- [x] integrate and expose Toolbar component
- [x] write documentation
- [x] add vulnerabilities and dependencies badge
- [x] update issue template (show steps as interactions from an empty Sheet)
- [x] Refactor codebase: use Delta [AttributeMap](https://github.com/quilljs/delta/blob/master/src/AttributeMap.ts) and [Op](https://github.com/quilljs/delta/blob/master/src/Op.ts)
- [x] Refactor: get rid of deprecated lifecycle methods in Sheet
- [x] Include GIF in readme
- [x] Publish debugger
- [x] Refactor: use named exports only
- [x] Use prettier
